### ISSUE TITLE
Spaces in file names get replaced with %20

### ISSUE THREAD

**Issue by doct** [watermelonwolverine/fvttmv#1]
platform: windows/powershell/python 3.10 from windows app store

Moving a file from one directory into another converts spaces in file names into %20. This leads to broken references within foundry client.

fvttmv should not change characters within file names.

(Thanks for the great tool, btw., very handy! :-) )

**Comment by watermelonwolverine** [comment]
I wasn't able to replicate the issue although it did lead me to a lot of other issues that were hidden in the code. 

Can you check if the problem persists after an update? 

If it does persists please elaborate a bit:

1. What was the file tree before and after.
2. What was the exact command string that you used?
3. Try adding the "--verbose-debug" argument (warning: this slows down the process a lot so use this on a small folder) and post the first few lines.

**Comment by doct** [comment]
Thanks for looking into it, and so quickly!

With the new version I can't reproduce it either, so thanks for fixing it! :-)

All the best!
